CadProf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tbook import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # as minhas urls
    url(r'^$', views.index, name='index'),
    url(r'^', include('tbook.urls', namespace='tbook')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
        )

tbook/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^todos_anos_letivos/$',
        views.all_school_years_func, name='all_school_years'
        ),
    url(r'^todas_escolas/$',
        views.all_schools_func, name='all_schools'
        ),
    url(r'^(?P<slug>[\w_-]+)/$', views.index, name='index1'),
    url(
        r'^(?P<school_year_slug>[\w_-]+)/(?P<school_class_slug>[\w_-]+)/$',
        views.school_class_func, name='schoolclass'
    ),
    url(r'^(?P<school_year_slug>[\w_-]+)/(?P<school_class_slug>[\w_-]+)/(?P<slug>[\w_-]+)/$',
        views.student_profile_func, name='student'
        ),
]

tbook/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import date
from phonenumber_field.modelfields import PhoneNumberField


class SchoolYear(models.Model):
    ''' um modelo para o ano letivo'''

    designation = models.CharField('Designação', max_length=200)

    slug = models.SlugField('Caminho')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.designation

    def get_absolute_url(self):
        return reverse('tbook:index1', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'Ano Letivo'
        verbose_name_plural = 'Anos Letivos'
        ordering = ['designation']


class SchoolTerm(models.Model):
    ''' um modelo para o período escolar'''

    DESIGNATION_CHOICES = (
        ("1º Período", "1º Período"), ("2º Período", "2º Período"),
        ("3º Período", "3º Período"),
    )

    designation = models.CharField(
        'Designação', choices=DESIGNATION_CHOICES, max_length=100,
        default='1ºPeríodo'
    )
    start_date = models.DateField('Início')
    end_date = models.DateField('Fim')
    school_year = models.ForeignKey(
        'tbook.SchoolYear', verbose_name='Ano Letivo', on_delete=models.CASCADE
    )

    slug = models.SlugField('Caminho')
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.designation

    class Meta:
        verbose_name = 'Período'
        verbose_name_plural = 'Períodos'
        ordering = ['start_date']


class School(models.Model):
    ''' Um modelo para a escola'''

    name = models.CharField('Designação', max_length=200)
    code = models.IntegerField('Código da Escola', blank=True)
    adress = models.TextField('Morada', blank=True)
    phone = PhoneNumberField(blank=True)
    admin_email = models.EmailField(
        'Email Direção', max_length=254, unique=True, blank=True
    )
    sevices_email = models.EmailField(
        'Email Secretaria', max_length=254, unique=True, blank=True
    )
    slug = models.SlugField('Caminho')

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Escola'
        verbose_name_plural = 'Escolas'
        ordering = ['name']


class Subject(models.Model):
    ''' um modelo para a disciplina'''

    DESIGNATION_CHOICES = (
        ("Matemática", "Matemática"), ("Física", "Física"),
        ("Química", "Química"), ('Físico-Química', 'Físico-Química'),
        ("Outra", "Outra"),
    )
    SIGLA_CHOICES = (
        ("Mat", "Mat"), ("Fis", "Fis"), ("Quim", "Quim"), ("FQ", "FQ"),
        ("Outra", "Outra"),
    )

    designation = models.CharField(
        'Designação', choices=DESIGNATION_CHOICES, max_length=100,
        default='Física'
    )
    sigla = models.CharField(
        'Nome Curto', choices=SIGLA_CHOICES, max_length=100, default='Fis'
    )
    slug = models.SlugField('Caminho')

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.designation

    class Meta:
        verbose_name = 'Disciplina'
        verbose_name_plural = 'Disciplinas'
        ordering = ['designation']


class SchoolClass(models.Model):
    ''' um modelo para o registo das turmas'''

    YEAR_IN_SCHOOL_CHOICES = (
        ("7ºano", "7º Ano"), ("8ºano", "8º Ano"),
        ("9ºano", "9º Ano"), ("10ºano", "10º Ano"),
        ("11ºano", "11º Ano"), ("12ºano", "12º Ano"),
    )

    school_year = models.ForeignKey(
        'tbook.SchoolYear', verbose_name='Ano Letivo', on_delete=models.CASCADE
    )
    school = models.ForeignKey(
        'tbook.School', verbose_name='Escola', on_delete=models.CASCADE
    )
    subject = models.ForeignKey(
        'tbook.Subject', verbose_name='Disciplina', on_delete=models.CASCADE
    )
    designation = models.CharField('Designação', max_length=50)
    slug = models.SlugField('Caminho')
    year_in_school = models.CharField(
        'Ano', choices=YEAR_IN_SCHOOL_CHOICES, max_length=100, default='7º Ano'
    )
    max_students = models.IntegerField('máx alunos', default=25)
    teacher_in_charge = models.CharField(
        'Diretor de Turma', max_length=100, blank=True
    )
    tc_email = models.EmailField(
        'Email DT', max_length=254, unique=True, blank=True
    )

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.designation

    def get_absolute_url(self):
        ano_letivo = SchoolYear.objects.get(id=self.school_year.id)
        return reverse('tbook:schoolclass', kwargs={
            'school_year_slug': ano_letivo.slug,
            'school_class_slug': self.slug
            })

    class Meta:
        verbose_name = 'Turma'
        verbose_name_plural = 'Turmas'
        ordering = ['designation']


class Student(models.Model):
    ''' modelo para os alunos da turma'''

    SEX_CHOICES = (("M", "Masculino"), ("F", "Feminino"),)

    school_class = models.ForeignKey(
        'tbook.SchoolClass', verbose_name='Turma', on_delete=models.CASCADE
    )
    name = models.CharField('Nome', max_length=100)
    birth_date = models.DateField('Data de Nascimento')
    sex = models.CharField(
        'sexo', choices=SEX_CHOICES, max_length=100, default='7º Ano'
    )
    email = models.EmailField('Email', max_length=254, unique=True)
    phone = PhoneNumberField('Telefone', blank=True)
    adress = models.TextField('Morada', blank=True)
    number = models.IntegerField('Número na turma')
    foto = models.ImageField(
        'Foto', upload_to='media/fotos_alunos/',
        default='media/fotos_alunos/no-img.jpg'
    )
    nee = models.BooleanField('NEE', default=False)
    notes = models.TextField('Observações', blank=True)

    tutor = models.CharField('Enc.Educação', max_length=100)
    t_email = models.EmailField(
        'Email EE', max_length=254, unique=True, blank=True
    )
    t_phone = PhoneNumberField('Telefone EE', blank=True)

    slug = models.SlugField('Caminho')

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.name

    def get_age(self):
        ''' calculate age from actual date an birth_date'''
        today = date.today()
        return today.year - self.birth_date.year - \
            ((today.month, today.day) <
                (self.birth_date.month, self.birth_date.day))

    def get_first_name(self):
        return str(self).split(" ")[0]

    def get_last_name(self):
        return str(self).split(" ")[-1]

    def get_absolute_url(self):
        turma = SchoolClass.objects.get(id=self.school_class.id)
        ano_letivo = SchoolYear.objects.get(id=turma.school_year.id)
        return reverse('tbook:student', kwargs={
            'school_year_slug': ano_letivo.slug,
            'school_class_slug': turma.slug,
            'slug': self.slug
        })

    # ver o site seguinte para tentar por a funcionar
    # as imagens formatadas no tamanho:
    # https://github.com/vinyll/django-imagefit

    class Meta:
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'
        ordering = ['school_class']

tbook/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from .models import SchoolYear, SchoolTerm, School, SchoolClass, Student


def index(request, **kargs):
    '''apresenta dados do ano letivo currente na página inicial se apenas
    for dado um argumento. Se forem passados dois argumentos apresenta o ano
    letivo selecionado'''

    if kargs:
        slug = kargs.get('slug')
        current_school_year = SchoolYear.objects.get(slug=slug)
    else:
        current_school_year = SchoolYear.objects.latest('created')

    template_name = 'tbook/index.html'
    side_bar_school_years = SchoolYear.objects.order_by('-id')[:3]
    school_terms = SchoolTerm.objects.filter(
        school_year=current_school_year
    ).order_by('designation')
    school_classes = SchoolClass.objects.filter(
        school_year=current_school_year
    )
    students = []
    school_classes_dict = {}
    total_students = 0
    for shc in school_classes:
        s = Student.objects.filter(school_class=shc)
        students.append(s)
        school_classes_dict.update({shc: s.count()})
        total_students = total_students + s.count()

    mail_students = 0
    for stds in students:
        for s in stds:
            if s.sex == 'M':
                mail_students += 1

    fem_students = total_students - mail_students

    context = {
        'current_school_year': current_school_year,
        'side_bar_school_years': side_bar_school_years,
        'school_terms': school_terms,
        'school_classes_dict': school_classes_dict,
        'students': students,
        'total_students': total_students,
        'mail_students': mail_students,
        'fem_students': fem_students,
    }
    return render(request, template_name, context)


def school_class_func(request, school_year_slug, school_class_slug):
    ''' apresenta os dados da turma selecionada'''

    template_name = 'tbook/school_class_page.html'
    school_class = SchoolClass.objects.get(slug=school_class_slug)

    current_school_year = SchoolYear.objects.get(slug=school_year_slug)
    side_bar_school_years = SchoolYear.objects.order_by('-id')[:3]
    school_terms = SchoolTerm.objects.filter(
        school_year=current_school_year
    ).order_by('designation')
    students = Student.objects.filter(school_class=school_class)
    total_students = students.count()
    school_classes_dict = SchoolClass.objects.filter(
        school_year=current_school_year
    )

    context = {
        'current_school_year': current_school_year,
        'side_bar_school_years': side_bar_school_years,
        'school_terms': school_terms,
        'school_class': school_class,
        'students': students,
        'total_students': total_students,
        'school_classes_dict': school_classes_dict,
    }
    return render(request, template_name, context)


def student_profile_func(request, school_year_slug, school_class_slug, slug):
    ''' apresenta a ficha completa de cada aluno'''

    template_name = 'tbook/student_profile.html'
    student = Student.objects.get(slug=slug)
    school_class = SchoolClass.objects.get(slug=school_class_slug)

    current_school_year = SchoolYear.objects.get(slug=school_year_slug)
    side_bar_school_years = SchoolYear.objects.order_by('-id')[:3]
    school_classes_dict = SchoolClass.objects.filter(
        school_year=current_school_year
    )

    context = {
        'current_school_year': current_school_year,
        'side_bar_school_years': side_bar_school_years,
        'school_class': school_class,
        'school_classes_dict': school_classes_dict,
        'student': student,
    }
    return render(request, template_name, context)


def all_school_years_func(request):
    ''' Apresenta todos os registos de anos letivos guardados na base de
    dados da aplicação'''

    template_name = 'tbook/all_school_years.html'
    all_school_years = SchoolYear.objects.all().order_by('-created')

    context = {
        'all_school_years': all_school_years,
    }
    return render(request, template_name, context)


def all_schools_func(request):
    ''' Apresenta todas as Escolas guardadas na base de dados do sistema'''

    template_name = 'tbook/all_schools.html'
    all_schools = School.objects.all().order_by('-created')
    side_bar_school_years = SchoolYear.objects.order_by('-id')[:3]

    context = {
        'all_schools': all_schools,
        'side_bar_school_years': side_bar_school_years,
    }
    return render(request, template_name, context)


def alunos(request, school_year_slug, turma_slug):
    template_name = 'tbook/alunos.html'
    ano_letivo = SchoolYear.objects.get(slug=school_year_slug)
    turma = SchoolClass.objects.get(slug=turma_slug)
    alunos = Student.objects.filter(school_class=turma)

    context = {
        'ano_letivo': ano_letivo,
        'turma': turma,
        'alunos': alunos
    }
    return render(request, template_name, context)


def aluno(request, school_year_slug, turma_slug, slug):
    template_name = 'tbook/aluno.html'
    ano_letivo = SchoolYear.objects.get(slug=school_year_slug)
    turma = SchoolClass.objects.get(slug=turma_slug)
    aluno = Student.objects.get(slug=slug)

    context = {
        'ano_letivo': ano_letivo,
        'turma': turma,
        'aluno': aluno
    }
    return render(request, template_name, context)

tbook/templates/tbook/all_school_years.html
{% extends "tbook/base.html" %}

{% block principal %}

        <!-- page content -->
        <div class="right_col" role="main">

          <!-- top tiles -->
          <div class="row tile_count">
            <div class="col-md-6 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-briefcase"></i> Registos de</span>
              <div class="count">Anos Letivos</div>
              <span class="count_bottom"><i class="green">todos os Anos Letivos</i> </span>
            </div>
            <a class="btn btn-app" style="float: right;">
              <i class="fa fa-briefcase"></i> adicionar Ano Letivo
            </a>
          </div>
          <!-- /top tiles -->

          <!-- todos os Anos Letivos -->
          {% if all_school_years %}
          {% for sy in all_school_years %}
          <a href="{{sy.get_absolute_url}}">
              <div class="animated flipInY col-lg-4 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-briefcase"></i>
                  </div>
                  <div class="col-md-8 tile">
                      <h2>{{sy.designation}}</h2>
                      <p><i class="green">criado em: </i> {{sy.created}}</p>
                      <p><i class="red">modificado em: </i> {{sy.modified}}</p>
                  </div>
                </div>
              </div>
          </a>
          {% endfor %}
          {% else %}
            <p>sem registos</p>
          {% endif %}
          <!-- /todos os Anos Letivos -->

          <br />
        </div>
        <!-- /page content -->

{% endblock %}

tbook/templates/tbook/all_schools.html
{% extends "tbook/base.html" %}

{% block principal %}

        <!-- page content -->
        <div class="right_col" role="main">

          <!-- top tiles -->
          <div class="row tile_count">
            <div class="col-md-6 col-sm-4 col-xs-6 tile_stats_count">
              <span class="count_top"><i class="fa fa-briefcase"></i> Registos de</span>
              <div class="count">Escolas</div>
              <span class="count_bottom"><i class="green">todas as Escolas</i> </span>
            </div>
            <a class="btn btn-app" style="float: right;">
              <i class="fa fa-hospital-o"></i> adicionar Escola
            </a>
          </div>
          <!-- /top tiles -->

          <!-- todos as Escolas -->
          {% if all_schools %}
          {% for s in all_schools %}

          <div class="col-md-4 col-xs-12 ">
            <div class="x_panel fixed_height_390">
              <div class="x_title">
                <h2>{{s.name}}</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Editar</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>

              <div class="x_content">
                <div>
                  <ul class="list-inline widget_tally">
                    <li>
                      <p>
                        <span class="month">Código de Escola </span>
                        <span class="count">{{s.code}}</span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Morada</span>
                        <span class="count">{{s.adress}} </span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Telefone </span>
                        <span class="count">{{s.phone}}</span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Email Direção </span>
                        <span class="count">{{s.admin_email}}</span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Email Secretaria </span>
                        <span class="count">{{s.services_email}}</span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Criado em </span>
                        <span class="count">{{s.created}}</span>
                      </p>
                    </li>
                    <li>
                      <p>
                        <span class="month">Modificado em </span>
                        <span class="count">{{s.modified}}</span>
                      </p>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          {% else %}
            <p>sem registos</p>
          {% endif %}
          <!-- /todas as Escolas -->

          <br />
        </div>
        <!-- /page content -->

{% endblock %}

tbook/templates/tbook/aluno.html
{% if aluno %}
    <h2> Caderneta do Professor </h2>
    <h4> Turma {{turma}} de {{ano_letivo.designation}}</h4>
    <ul>
        <li>{{aluno.number}} - {{ aluno.name }} </li>
        <li>{{aluno.birth_date}} - {{ aluno.get_age }} </li>
        <li>{{ aluno.get_first_name }} - {{aluno.get_last_name}}   </li>
        <li>{{aluno.email}} </li>
        <li>{{aluno.tutor}}  </li>
        <li>{{aluno.created}} </li>
        <li>{{ aluno.modified }} </li>

    </ul>
{% else %}
    <p>Sem dados.</p>
{% endif %}
    <p><a href="/"> Voltar </a></p>

tbook/templates/tbook/alunos.html
{% if alunos %}
    <h2> Caderneta do Professor </h2>
    <h4> Turma {{turma}} de {{ano_letivo.designation}}</h4>
    <ul>
    {% for a in alunos %}
        <li>{{a.number}} -
            <a href="{{a.get_absolute_url}}">
                {{ a.name }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Turma sem alunos.</p>
{% endif %}
    <p><a href="/"> Voltar </a></p>

tbook/templates/tbook/sidebar.html
{% load static %}

{% block sidebar %}

<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="/" class="site_title"><i class="fa fa-book"></i>
          <span>CadProf-Pro!</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <img src=" {% static "prof.jpg" %}" alt="..." class="img-circle profile_img">
      </div>
      <div class="profile_info">
        <span>Bem vindo,</span>
        <h2>professor X</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>Separadores</h3>
        <ul class="nav side-menu">

          <li><a><i class="fa fa-briefcase"></i> Anos Letivos <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
            {% if side_bar_school_years %}
            {% for al in side_bar_school_years %}
                <li><a href="{{al.get_absolute_url}}">{{ al.designation }}</a></li>
            {% endfor %}
                <li><a href="{% url 'tbook:all_school_years' %}">Ver todos</a></li>
            {% endif %}
                <li><a href="#">Adicionar</a></li>
            </ul>
          </li>
          {% if current_school_year %}
          <li><a><i class="fa fa-server"></i> Turmas [{{current_school_year.designation}}]<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
            {% if school_classes_dict %}
                {% for t in school_classes_dict %}
                  <li><a href="{{t.get_absolute_url}}">{{ t.designation }}</a></li>
                {% endfor %}
            {% endif %}
                <li><a href="#">Adicionar</a></li>
            </ul>
           </li>
           {% endif %}
           <li><a><i class="fa fa-hospital-o"></i> Escolas<span class="fa fa-chevron-down"></span></a>
             <ul class="nav child_menu">
            {% if not all_schools %}
               <li><a href="{% url 'tbook:all_schools' %}">Ver todas</a></li>
            {% endif %}
               <li><a href="#">Adicionar</a></li>
             </ul>
           </li>

        </ul>
      </div>



    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      </a>
    </div>
    <!-- /menu footer buttons -->
  </div>
</div>

{% endblock %}

tbook/templates/tbook/turmas.html
{% if turmas %}
    <h2> Caderneta do Professor </h2>
    <h4> Turmas de {{AnoLetivo.designation}}</h4>
    <ul>
    {% for t in turmas %}
        <li><a href="{{t.get_absolute_url}}">{{ t.designation }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há registos de turmas.</p>
{% endif %}
    <p><a href="/"> Voltar </a></p>